@authToken="4e83f09a85da7c8ab5f29acf555139ea"


### Asking for new definition
POST https://api.decorebator.com/static/workers/definition/69
Authorization: 4e83f09a85da7c8ab5f29acf555139ea


### Asking for new image
POST https://api.decorebator.com/static/workers/imageGenerator/151
Authorization: 4e83f09a85da7c8ab5f29acf555139ea

