@email="lsimaocosta@gmail.com"
@password= "12345"


### Creating user
POST https://api.decorebator.com/users
content-type: application/json

{
"FirstName":"Lucas",
"LastName":"Simao",
"Email": {{email}},
"Password": {{password}}
}

### Login
# @name loginRequest
POST https://api.decorebator.com/login
content-type: application/json

{
"Email": {{email}},
"Password": {{password}}
}

@authToken = {{loginRequest.response.headers.Authorization}}

### Get wordlists
GET https://api.decorebator.com/wordlists
authorization: {{authToken}}



### Creating wordlist
# @name wordlistRequest
POST https://api.decorebator.com/wordlists
authorization: {{authToken}}

{
"Name":"Deep Utopia",
"LanguageCode":"en"
}

@wordlistId = {{wordlistRequest.response.body.id}} 

### Creating word
POST https://api.decorebator.com/wordlists/{{wordlistId}}/words
authorization: {{authToken}}

{
 "Name":"wherefore"  
}



### Generating a quiz
POST http://localhost:3000/wordlists/{{wordlistId}}/quizzes
authorization: {{authToken}}

{
}

### Saving quiz result
PATCH https://api.decorebator.com/wordlists/{{wordlistId}}/quizzes
authorization: {{authToken}}

{
    "success": true,
    "id":2
}