@email="lsimaocosta@gmail.com"
@password= "12345"


### Creating user
POST https://api.decorebator.com/users
content-type: application/json

{
"FirstName":"Test 1",
"LastName":"xpto",
"Email": {{email}},
"Password": {{password}}
}

### Login
# @name loginRequest
POST https://api.decorebator.com/login
content-type: application/json

{
"Email": {{email}},
"Password": {{password}}
}

@authToken = {{loginRequest.response.headers.authorization}}

### Listing wordlists
# @name wordlistRequest
GET https://api.decorebator.com/wordlists
authorization: {{authToken}}


### Creating wordlist
# @name wordlistRequest
POST https://api.decorebator.com/wordlists
authorization: {{authToken}}

{
"Name":"tests",
"description":"tests only"
}

@wordlistId = {{wordlistRequest.response.body.id}} 
@wordlistId = 34

### Creating word
POST https://api.decorebator.com/wordlists/{{wordlistId}}/words
authorization: {{authToken}}

{
 "Name":"Slip up"  
}



### Generating a quiz
POST https://api.decorebator.com/wordlists/{{wordlistId}}/quizzes
authorization: {{authToken}}

{
}

### Saving quiz result
PATCH https://api.decorebator.com/wordlists/{{wordlistId}}/quizzes
authorization: {{authToken}}

{
    "success": true,
    "id":30
}




### Publish wordlist
# @name Publish
POST https://api.decorebator.com/wordlists/3150/publish
content-type: application/json
authorization: {{authToken}}

{
"title":"For Whom The Bell Tolls",
"description":"novel by Ernest Hemingway",
"difficulty":"medium",
"timeLimitMinutes":10
}

### Publish wordlist
GET https://api.decorebator.com/public-quizzes/for-whom-the-bell-tolls