// Code generated by MockGen. DO NOT EDIT.
// Source: internal/common/worker_trigger.go
//
// Generated by this command:
//
//	mockgen -destination /home/lucas/workspace/decorebator-v2/api/internal/tests/mocks/worker_trigger.go -package mocks -source=internal/common/worker_trigger.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerTrigger is a mock of WorkerTrigger interface.
type MockWorkerTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerTriggerMockRecorder
}

// MockWorkerTriggerMockRecorder is the mock recorder for MockWorkerTrigger.
type MockWorkerTriggerMockRecorder struct {
	mock *MockWorkerTrigger
}

// NewMockWorkerTrigger creates a new mock instance.
func NewMockWorkerTrigger(ctrl *gomock.Controller) *MockWorkerTrigger {
	mock := &MockWorkerTrigger{ctrl: ctrl}
	mock.recorder = &MockWorkerTriggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerTrigger) EXPECT() *MockWorkerTriggerMockRecorder {
	return m.recorder
}

// TriggerDefinitionFetcher mocks base method.
func (m *MockWorkerTrigger) TriggerDefinitionFetcher(wordId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerDefinitionFetcher", wordId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerDefinitionFetcher indicates an expected call of TriggerDefinitionFetcher.
func (mr *MockWorkerTriggerMockRecorder) TriggerDefinitionFetcher(wordId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerDefinitionFetcher", reflect.TypeOf((*MockWorkerTrigger)(nil).TriggerDefinitionFetcher), wordId)
}

// TriggerImageGenerator mocks base method.
func (m *MockWorkerTrigger) TriggerImageGenerator(definitionId int64, customPrompt string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerImageGenerator", definitionId, customPrompt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerImageGenerator indicates an expected call of TriggerImageGenerator.
func (mr *MockWorkerTriggerMockRecorder) TriggerImageGenerator(definitionId, customPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerImageGenerator", reflect.TypeOf((*MockWorkerTrigger)(nil).TriggerImageGenerator), definitionId, customPrompt)
}

// TriggerTextToSpeech mocks base method.
func (m *MockWorkerTrigger) TriggerTextToSpeech(wordId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerTextToSpeech", wordId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerTextToSpeech indicates an expected call of TriggerTextToSpeech.
func (mr *MockWorkerTriggerMockRecorder) TriggerTextToSpeech(wordId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerTextToSpeech", reflect.TypeOf((*MockWorkerTrigger)(nil).TriggerTextToSpeech), wordId)
}
