name: decorebator-test
services:
  redis:
    image: redis/redis-stack-server:latest
  minio:
    image: minio/minio:latest
    env_file:
      - .env.test
    command: server /data --console-address ":9001" 
  main:
    image: golang:1.23.1
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app    
      - /home/lucas/go/pkg/mod:/go/pkg/mod # '/home/lucas/go/pkg/mod' comes from `go env GOMODCACHE`
    working_dir: /app
    command: go test -v ./...
    env_file:
      - .env.test
  postgres:
    image: postgres:15.3
    env_file:
      - .env.test 
