name: decorebator-test
services:
  
  redis:
    image: redis/redis-stack-server:latest

  minio:
    image: minio/minio:latest
    env_file:
      - .env.test
    command: server /data --console-address ":9001"   

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/decorebator;
      mc anonymous set download myminio/decorebator;
      sleep infinity;"
  main:
    image: golang:1.22
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app    
      - /home/lucas/go/pkg/mod:/go/pkg/mod # '/home/lucas/go/pkg/mod' comes from `go env GOMODCACHE`
    working_dir: /app
    command: go test -coverprofile=coverage.out -cover -v ./...
    env_file:
      - .env.test
  postgres:
    image: postgres:15.3
    env_file:
      - .env.test 
