version: '3.9'

services:
  postgres:
    image: postgres:15.3
    restart: on-failure
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
